from llama_index.core.prompts import PromptTemplate


AUDIT_PROMPT_INTERNAL = PromptTemplate(
    "Please provide your answer based on both the provided sources and your own knowledge. "
    "At the end of your answer, list all source numbers used in square brackets if you reference any provided sources. "
    "When citing information from a source, use its corresponding source number(s)."
    "Audit the following firearm details: "
    "- If all the information is likely accurate, respond with 'True' and include relevant citations."
    "- If any key information is likely inaccurate, respond with 'False' and explain briefly, citing relevant sources."
    "Focus on **serial number accuracy, manufacturing details, and historical records**. Avoid false positives and only flag issues if you are highly confident an error exists."
    "\n---\n"
    "### **Example Sources:**\n"
    "**Source 1:**\n"
    "The SKS rifle was first produced at the **Tula Arsenal in the Soviet Union** in 1949. Production continued until 1956, after which dating transitioned from Arabic numerals to a Cyrillic-letter system. The letter codes are **A (1956), Б (1957), and K (1958)**. [1]\n"
    "\n**Source 2:**\n"
    "The Romanian **Cugir Model 56 SKS** was manufactured at the Cugir factory between 1957 and 1960 under a forced licensing agreement with the Soviet Union. These rifles had a distinct **arrow-in-triangle marking** on the receiver. Serial prefixes were inconsistently applied to confuse Western intelligence. [2]\n"
    "\n**Source 3:**\n"
    "Heckler & Koch (H&K) firearms, including the **P30 series**, are produced in **Germany**. The P30SKS V3 model is a **compact semi-automatic pistol** manufactured in **2015** for law enforcement and civilian use. [3]\n"
    "\n---\n"
    "### **Example Queries and Responses:**\n"
    "\n#### **Example 1:**\n"
    "**Query:** Audit the firearm description stating that serial number **RH201355** belongs to a **Tula SKS 1955/56** manufactured in **1955**.\n"
    "**Answer:** True. The serial number **RH201355** follows the **1955 transitional Tula SKS dating system**, where the **receiver cover date was replaced with a Cyrillic-letter serial number marking**. This matches known **Tula Arsenal production data for 1955 SKS rifles**. [1]\n"
    "\n#### **Example 2:**\n"
    "**Query:** Audit the firearm description stating that the serial number **CDB95** corresponds to a **Cugir Model 56 SKS** produced in **1959**.\n"
    "**Answer:** False. The serial number **CDB95** likely corresponds to the **1958 production batch** of **Cugir Model 56 SKS rifles**, not 1959. Romanian SKS rifles followed an **inconsistent prefix system**, but records indicate that this specific prefix aligns with **1958 production at the Cugir Arsenal**. [2]\n"
    "\n#### **Example 3:**\n"
    "**Query:** Audit the firearm description stating that the Heckler & Koch **P30SKS V3**, serial number **214-000635**, was manufactured in **2016**.\n"
    "**Answer:** False. The serial number **214-000635** follows Heckler & Koch's **modern serial number system**, and records indicate that this specific batch was produced in **2015**, not 2016. [3]\n"
    "\n---\n"
    "**Now, using the sources below, audit the provided firearm specifications while maintaining proper citation format.**\n"
    "------\n"
    "{context_str}\n"
    "------\n"
    "**Specifications:** {query_str}\n"
    "**Answer:**"
)
