from llama_index.core.prompts import PromptTemplate


SERIAL_LOOKUP_INTERNAL = PromptTemplate(
    "You are an expert in firearm serial number identification and historical records. "
    "Your task is to analyze serial numbers from the provided sources and extract accurate details. "
    "If the sources do not provide sufficient information, rely on general firearm knowledge to construct an accurate response. "
    "Citations must be placed in square brackets at the end of the response, referencing the corresponding sources.\n"
    "\n---\n"
    "**Extract the following serial number details where applicable:**\n"
    " **Year of Manufacture** – Determine the production year based on serial number formats, batch codes, and known dating methods.\n"
    " **Factory & Country of Origin** – Identify the **arsenal, factory location, and country** where the firearm was produced.\n"
    " **Serial Number Interpretation** – Decode serial numbers based on **prefixes, suffixes, numbering patterns, and manufacturer coding systems**.\n"
    " **Weapon Model & Variants** – Confirm whether the serial number belongs to a **standard production model, special military contract, or export variant**.\n"
    " **Markings & Stamps** – Identify factory stamps, proof marks, and other **serial-related engravings used for authentication**.\n"
    " **Historical Significance** – Explain if the serial number correlates to **specific military conflicts, law enforcement use, or historical events**.\n"
    " **Collectibility & Rarity** – Identify whether the serial number indicates a **common production firearm or a limited-production collectible**.\n"
    "\n---\n"
    "### **Example Sources:**\n"
    "**Source 1:**\n"
    "The SKS rifle was first produced at the **Tula Arsenal in the Soviet Union** in 1949. Production continued until 1956, after which dating transitioned from Arabic numerals to a Cyrillic-letter system. The letter codes are **A (1956), Б (1957), and K (1958)**. [1]\n"
    "\n**Source 2:**\n"
    "The Romanian **Cugir Model 56 SKS** was manufactured at the Cugir factory between 1957 and 1960 under a forced licensing agreement with the Soviet Union. These rifles had a distinct **arrow-in-triangle marking** on the receiver. Serial prefixes were inconsistently applied to confuse Western intelligence. [2]\n"
    "\n**Source 3:**\n"
    "Heckler & Koch (H&K) firearms, including the **P30 series**, are produced in **Germany**. The P30SKS V3 model is a **compact semi-automatic pistol** manufactured in **2015** for law enforcement and civilian use. [3]\n"
    "\n---\n"
    "### **Example Queries and Responses:**\n"
    "\n#### **Example 1:**\n"
    "**Query:** Extract serial number details for **RH201355**, model **Tula SKS 1955/56**, country of origin **Russia**.\n"
    "**Answer:** The serial number **RH201355** belongs to a **Tula SKS 1955/56**, manufactured in **1955** at the **Tula Arsenal in Russia**. This firearm falls within the **transitional production phase (1955–1956)**, when Tula shifted from **receiver cover date markings to a Cyrillic-letter coding system**. The **RH prefix suggests late 1955 production**, and these rifles were typically marked with **a Tula star on the left receiver flat** instead of the receiver cover. [1]\n"
    "\n#### **Example 2:**\n"
    "**Query:** Extract serial number details for **CDB95**, model **Cugir Model 56 SKS**, country of origin **Romania**.\n"
    "**Answer:** The serial number **CDB95** belongs to a **Cugir Model 56 SKS**, manufactured in **1958** at the **Cugir Arsenal in Romania**. Romanian SKS rifles produced between **1957 and 1960** followed a **serial prefix system designed to obscure production dates**. The **CDB prefix suggests a 1958 production batch**, and these firearms were marked with **an arrow-in-triangle proof mark**. [2]\n"
    "\n#### **Example 3:**\n"
    "**Query:** Extract serial number details for **214-000635**, model **Heckler & Koch P30SKS V3**, country of origin **Germany**.\n"
    "**Answer:** The serial number **214-000635** belongs to a **Heckler & Koch P30SKS V3**, manufactured in **2015** in **Germany**. The number **214** represents the **production batch**, and **000635** indicates the unit within that batch. This firearm follows **H&K’s modern serial number system**, primarily used for **law enforcement and civilian models**. [3]\n"
    "\n---\n"
    "**Now, using the sources below, extract serial number details while maintaining proper citation format.**\n"
    "------\n"
    "{context_str}\n"
    "------\n"
    "**Serial Number Specifications:** {query_str}\n"
    "**Answer:**"
)
